services:
  - type: web
    name: spotify-login-demo
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NEXT_PUBLIC_SPOTIFY_CLIENT_ID
        sync: false
      - key: NEXT_PUBLIC_SPOTIFY_CLIENT_SECRET
        sync: false
      - key: NEXT_PUBLIC_SPOTIFY_REDIRECT_URI
        sync: false
